spec:
  type: url
  targets:
    - ../../.catalog-info/component-my-app.yaml
    - ../../.catalog-info/my-app-api.yaml
  presence: required
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-data
