spec:
  type: openapi
  lifecycle: production
  owner: my_team
  system: system
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
    ...
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my_app_api
  namespace: default
  title: API